/**
 * 화면 프로토타입용 mock 데이터 — 시각 정본(docs/design/mockup)과 동일한 내용.
 * FE 연동 시 이 모듈의 export를 API 호출(react-query)로 교체한다.
 *   - 메인:   GET /api/news (✅완료), GET /api/market/kr/major-sectors (✅완료), /api/analysis/recent
 *   - 분석:   GET /api/analysis/:id  →  AnalysisResult
 */
import type { AnalysisResult, FloatingChip, RecentAnalysis } from '@/lib/types';

/* ── 메인: 최근 분석 내역 (F-03c) ────────────────────────── */
export const recentAnalyses: RecentAnalysis[] = [
  {
    id: 'robotaxi',
    title: '테슬라 로보택시 공개 임박…자율주행 밸류체인 재조명',
    analyzedAt: '어제',
    originUrl: 'https://example.com/news/robotaxi',
  },
  {
    id: 'memory-price',
    title: '메모리 반도체 가격 3분기 연속 상승',
    analyzedAt: '3일 전',
    originUrl: 'https://example.com/news/memory-price',
  },
  {
    id: 'defense-export',
    title: '방산 수출 사상 최대…관련주 재평가 흐름',
    analyzedAt: '지난주',
    originUrl: 'https://example.com/news/defense-export',
  },
];

/* ── 로딩: 부유 키워드 칩 ───────────────────────────────── */
export const floatingChips: FloatingChip[] = [
  { label: '# HBM4', tone: 'neutral', x: 22, y: 12, delay: 0 },
  { label: '# 엔비디아', tone: 'neutral', x: 58, y: 20, delay: 0.8 },
  { label: '전기장비', tone: 'teal', x: 8, y: 32, delay: 1.6 },
  { label: '반도체', tone: 'positive', x: 78, y: 44, delay: 0.4 },
  { label: '# TC본더', tone: 'neutral', x: 6, y: 62, delay: 2.0 },
  { label: '# AI 데이터센터', tone: 'neutral', x: 60, y: 76, delay: 1.2 },
  { label: 'IT하드웨어', tone: 'blue', x: 30, y: 86, delay: 0.6 },
];

/* ── 분석 결과 (GET /api/analysis/:id) ──────────────────── */
export const analysisResult: AnalysisResult = {
  id: 'hbm4',
  sector: '반도체',
  verdict: '호재 분석',
  title: "SK하이닉스, 엔비디아 'HBM4' 단독 공급 계약 체결… 역대 최대 규모",
  source: '한국경제',
  publishedAt: '2026.07.05 12:10',
  desk: '산업부',
  analyzedAt: '2026.07.05 14:23',
  engineVersion: '수혜주.com AI v2.1',
  summary:
    "SK하이닉스가 엔비디아의 차세대 AI 가속기 '루빈(Rubin)'에 탑재될 6세대 고대역폭메모리 HBM4를 단독 공급하는 계약을 체결했다. 계약 규모는 역대 HBM 공급 계약 중 최대로, 2027년 말까지의 공급 물량이 사실상 확정된 것으로 알려졌다. 이번 수주로 SK하이닉스는 HBM 시장 점유율 1위 지위를 굳히는 동시에 청주 M15X 팹 증설 투자를 당초 계획보다 앞당길 방침이다. 증권가는 TC본더 등 적층 장비, 공정 소재, 테스트 등 후방 밸류체인 전반의 발주 확대가 뒤따를 것으로 전망하며, AI 데이터센터 증설 가속에 따라 전력기기·기판 업종까지 온기가 확산될 것으로 분석했다. 다만 경쟁사가 HBM4 품질 인증에 진입할 경우 공급 단가 인하 압력이 커질 수 있다는 점은 변수로 지목된다.",
  originUrl: 'https://www.hankyung.com',
  keywords: [
    '# HBM4',
    '# 엔비디아',
    '# SK하이닉스',
    '# AI 데이터센터',
    '# 첨단 패키징',
    '# TC본더',
  ],
  relatedSectors: [
    { name: '반도체', changePct: 8.4 },
    { name: 'IT하드웨어', changePct: 5.2 },
    { name: '전기장비', changePct: 3.1 },
    { name: '운송', changePct: -1.2 },
  ],
  reviewedCount: 42,
  goodSignal: {
    ratio: 72,
    headline: '관련 뉴스와 리포트에서는 긍정적인 해석이 더 많아요.',
    news: [
      { text: 'HBM4 공급 물량 2027년까지 사실상 확정', source: '한국경제' },
      { text: 'AI 가속기 수요 전망 일제히 상향', source: '매경' },
    ],
    reports: [
      { text: '"AI 사이클 초입, 목표가 상향"', source: '미래에셋' },
      { text: '"설비투자 수혜 뚜렷"', source: 'KB증권' },
    ],
    analyst: {
      name: '김OO 애널리스트',
      firm: '미래에셋',
      quote:
        '"AI 인프라 투자는 이제 시작 단계로, 반도체 장비 수요가 구조적으로 늘어날 전망입니다."',
    },
  },
  warnSignal: {
    ratio: 28,
    headline: '단기 과열이나 비용 부담을 우려하는 시각도 있어요.',
    news: [
      { text: '단기 급등 부담 지적', source: '이데일리' },
      { text: '밸류에이션 고평가 논란', source: '서울경제' },
    ],
    reports: [
      { text: '"단기 과열 구간 유의"', source: '하나증권' },
      { text: '"투자비 부담에 마진 압박 가능"', source: '신한' },
    ],
    analyst: {
      name: '이OO 애널리스트',
      firm: '하나증권',
      quote:
        '"기대는 크지만 실적이 뒷받침되지 못하면 변동성이 커질 수 있어 분할 접근이 필요합니다."',
    },
  },
  spreadNodes: [
    { id: 'origin', name: 'HBM4 수주 뉴스', tier: 0, row: 0.5 },
    { id: 'hbm', name: 'HBM·메모리', tier: 1, changePct: 8.4, row: 0.18 },
    { id: 'equip', name: '반도체 장비', tier: 1, changePct: 4.9, row: 0.5 },
    { id: 'dc', name: 'AI 데이터센터', tier: 1, changePct: 3.5, row: 0.82 },
    { id: 'pkg', name: '첨단 패키징·후공정', tier: 2, changePct: 4.8, row: 0.08 },
    { id: 'material', name: '반도체 소재', tier: 2, changePct: 3.4, row: 0.3 },
    { id: 'test', name: '테스트·계측', tier: 2, changePct: 2.6, row: 0.5 },
    { id: 'server', name: 'AI 서버·기판', tier: 2, changePct: 3.9, row: 0.7 },
    { id: 'power', name: '전력기기', tier: 2, changePct: 3.7, row: 0.9 },
    { id: 'gas', name: '특수가스·케미컬', tier: 3, changePct: 1.8, row: 0.16 },
    { id: 'cooling', name: '냉각·열관리', tier: 3, changePct: 2.2, row: 0.44 },
    { id: 'grid', name: '전력망·ESS', tier: 3, changePct: 2.1, row: 0.68 },
    { id: 'wire', name: '변압기·전선', tier: 3, changePct: 2.4, row: 0.9 },
  ],
  spreadEdges: [
    {
      from: 'origin',
      to: 'hbm',
      reason: 'HBM4 단독 공급으로 메모리 매출·점유율 직접 수혜',
      sources: [
        { title: 'HBM4 단독 공급 계약 체결', meta: '한국경제 · 06.02' },
        { title: 'HBM 시장 점유율 전망 상향', meta: '매일경제 · 06.04' },
      ],
    },
    {
      from: 'origin',
      to: 'equip',
      reason: 'M15X 팹 증설 앞당김 → 장비 발주 확대',
      sources: [{ title: '청주 M15X 증설 계획 조기 확정', meta: '한국경제 · 06.03' }],
    },
    {
      from: 'origin',
      to: 'dc',
      reason: 'AI 가속기 출하 확대 → 데이터센터 증설 가속',
      sources: [{ title: 'AI 데이터센터 투자 동향 점검', meta: '매일경제 · 06.05' }],
    },
    {
      from: 'hbm',
      to: 'pkg',
      reason: 'HBM 적층 물량 증가 → TC본더 등 후공정 수요 확대',
      sources: [{ title: '후공정 장비 발주 전망 상향', meta: '이데일리 · 06.07' }],
    },
    {
      from: 'hbm',
      to: 'material',
      reason: '생산 물량 확대 → 공정 소재 사용량 동반 증가',
      sources: [{ title: '반도체 소재 수급 타이트해져', meta: '서울경제 · 06.08' }],
    },
    {
      from: 'equip',
      to: 'test',
      reason: '장비 증설 → 수율 검증용 테스트·계측 수요 확대',
      sources: [{ title: '테스트 장비 시장 성장세 지속', meta: '전자신문 · 06.09' }],
    },
    {
      from: 'dc',
      to: 'server',
      reason: '데이터센터 증설 → AI 서버·고다층 기판 수요 증가',
      sources: [{ title: 'AI 서버 출하 전망 상향 조정', meta: '디지털타임스 · 06.10' }],
    },
    {
      from: 'dc',
      to: 'power',
      reason: '전력 소모 급증 → 전력기기 발주 확대',
      sources: [{ title: '데이터센터 전력 수요 급증', meta: '연합인포맥스 · 06.11' }],
    },
    {
      from: 'pkg',
      to: 'gas',
      reason: '후공정 가동률 상승 → 특수가스·케미컬 소비 증가',
      sources: [{ title: '특수가스 수요 확대 국면', meta: '머니투데이 · 06.12' }],
    },
    {
      from: 'server',
      to: 'cooling',
      reason: '고밀도 서버 발열 → 냉각·열관리 솔루션 수요',
      sources: [{ title: '액체 냉각 시장 전망 상향', meta: '전자신문 · 06.13' }],
    },
    {
      from: 'server',
      to: 'grid',
      reason: '전력 사용량 증가 → 전력망 증설·ESS 수요',
      sources: [{ title: '전력망 투자 확대 가속', meta: '연합인포맥스 · 06.14' }],
    },
    {
      from: 'power',
      to: 'wire',
      reason: '전력 인프라 투자 → 변압기·전선 수주 확대',
      sources: [{ title: '변압기 수출 동향 호조', meta: '한국경제 · 06.15' }],
    },
  ],
  // 실제 파이프라인과 동일하게 spreadNodes(tier≥1)에서 파생 — sector가 topStocks 키와 일치해 hover 툴팁 동작.
  heatmap: [
    { sector: 'HBM·메모리', changePct: 8.4, area: 'area0', weight: 1 },
    { sector: '반도체 장비', changePct: 4.9, area: 'area1', weight: 0.58 },
    { sector: 'AI 데이터센터', changePct: 3.5, area: 'area2', weight: 0.42 },
    { sector: '첨단 패키징·후공정', changePct: 4.8, area: 'area3', weight: 0.57 },
    { sector: '반도체 소재', changePct: 3.4, area: 'area4', weight: 0.4 },
    { sector: '테스트·계측', changePct: 2.6, area: 'area5', weight: 0.31 },
    { sector: 'AI 서버·기판', changePct: 3.9, area: 'area6', weight: 0.46 },
    { sector: '전력기기', changePct: 3.7, area: 'area7', weight: 0.44 },
    { sector: '특수가스·케미컬', changePct: 1.8, area: 'area8', weight: 0.21 },
    { sector: '냉각·열관리', changePct: 2.2, area: 'area9', weight: 0.26 },
    { sector: '전력망·ESS', changePct: 2.1, area: 'area10', weight: 0.25 },
    { sector: '변압기·전선', changePct: 2.4, area: 'area11', weight: 0.29 },
  ],
  knowledgeNodes: [
    { id: 'semi', name: '반도체', group: 'center', x: 50, y: 52 },
    { id: 'equip', name: '반도체 장비', group: 'tier1', x: 41, y: 56 },
    { id: 'hbm', name: 'HBM·메모리', group: 'tier1', x: 58, y: 62 },
    { id: 'pkg', name: '첨단 패키징', group: 'tier1', x: 55, y: 44 },
    { id: 'power', name: '전력기기', group: 'tier1', x: 52, y: 40 },
    { id: 'dc', name: 'AI 데이터센터', group: 'tier1', x: 42, y: 40 },
    { id: 'it', name: 'IT하드웨어', group: 'tier1', x: 38, y: 66 },
    { id: 'software', name: '소프트웨어', group: 'tier2', x: 44, y: 30 },
    { id: 'battery', name: '2차전지', group: 'tier2', x: 30, y: 74 },
    { id: 'autoparts', name: '자동차부품', group: 'tier2', x: 26, y: 66 },
    { id: 'test', name: '테스트·검사', group: 'tier2', x: 44, y: 78 },
    { id: 'display', name: '디스플레이', group: 'tier2', x: 40, y: 88 },
    { id: 'gas', name: '특수가스', group: 'tier2', x: 62, y: 68 },
    { id: 'car', name: '자동차', group: 'tier2', x: 72, y: 66 },
    { id: 'steel', name: '철강', group: 'etc', x: 80, y: 58 },
    { id: 'construction', name: '건설', group: 'etc', x: 74, y: 34 },
    { id: 'chemical', name: '화학', group: 'etc', x: 26, y: 42 },
    { id: 'grid', name: '전력망·ESS', group: 'tier2', x: 30, y: 46 },
    { id: 'wire', name: '변압기·전선', group: 'tier2', x: 64, y: 38 },
    { id: 'bio', name: '제약·바이오', group: 'etc', x: 66, y: 26 },
    { id: 'renewable', name: '신재생에너지', group: 'etc', x: 56, y: 20 },
    { id: 'stock', name: '증권', group: 'etc', x: 34, y: 22 },
    { id: 'retail', name: '유통', group: 'etc', x: 22, y: 28 },
    { id: 'game', name: '게임', group: 'etc', x: 24, y: 84 },
    { id: 'media', name: '미디어·엔터', group: 'etc', x: 58, y: 86 },
    { id: 'platform', name: '인터넷 플랫폼', group: 'etc', x: 52, y: 92 },
    { id: 'machine', name: '기계', group: 'tier2', x: 50, y: 46 },
  ],
  knowledgeEdges: [
    { from: 'semi', to: 'equip' },
    { from: 'semi', to: 'hbm' },
    { from: 'semi', to: 'pkg' },
    { from: 'semi', to: 'dc' },
    { from: 'semi', to: 'it' },
    { from: 'semi', to: 'power' },
    { from: 'semi', to: 'machine' },
    { from: 'equip', to: 'test' },
    { from: 'equip', to: 'chemical' },
    { from: 'hbm', to: 'gas' },
    { from: 'hbm', to: 'display' },
    { from: 'pkg', to: 'gas' },
    { from: 'pkg', to: 'wire' },
    { from: 'power', to: 'wire' },
    { from: 'power', to: 'grid' },
    { from: 'power', to: 'construction' },
    { from: 'dc', to: 'software' },
    { from: 'dc', to: 'grid' },
    { from: 'dc', to: 'renewable' },
    { from: 'it', to: 'battery' },
    { from: 'it', to: 'autoparts' },
    { from: 'it', to: 'platform' },
    { from: 'software', to: 'stock' },
    { from: 'software', to: 'game' },
    { from: 'battery', to: 'car' },
    { from: 'autoparts', to: 'car' },
    { from: 'car', to: 'steel' },
    { from: 'display', to: 'media' },
    { from: 'platform', to: 'media' },
    { from: 'retail', to: 'stock' },
    { from: 'bio', to: 'renewable' },
  ],
  topStocks: {
    'HBM·메모리': [
      { name: 'SK하이닉스', changePct: 8.9, code: '000660', market: 'KR' },
      { name: '삼성전자', changePct: 3.2, code: '005930', market: 'KR' },
      { name: '한미반도체', changePct: 7.4, code: '042700', market: 'KR' },
      { name: '디아이', changePct: 5.1, code: '003160', market: 'KR' },
      { name: '테크윙', changePct: 4.6, code: '089030', market: 'KR' },
    ],
    '반도체 장비': [
      { name: '한미반도체', changePct: 7.4, code: '042700', market: 'KR' },
      { name: '주성엔지니어링', changePct: 4.2, code: '036930', market: 'KR' },
      { name: '원익IPS', changePct: 3.8, code: '240810', market: 'KR' },
      { name: '피에스케이', changePct: 3.1, code: '319660', market: 'KR' },
      { name: '유진테크', changePct: 2.7, code: '084370', market: 'KR' },
    ],
    'AI 데이터센터': [
      { name: 'LS ELECTRIC', changePct: 4.4, code: '010120', market: 'KR' },
      { name: 'HD현대일렉트릭', changePct: 3.9, code: '267260', market: 'KR' },
      { name: '삼성물산', changePct: 2.2, code: '028260', market: 'KR' },
      { name: 'GS건설', changePct: 1.8, code: '006360', market: 'KR' },
      { name: 'SK가스', changePct: 1.1, code: '018670', market: 'KR' },
    ],
    '첨단 패키징·후공정': [
      { name: '한미반도체', changePct: 7.4, code: '042700', market: 'KR' },
      { name: '이오테크닉스', changePct: 5.5, code: '039030', market: 'KR' },
      { name: '하나마이크론', changePct: 4.8, code: '067310', market: 'KR' },
      { name: 'SFA반도체', changePct: 3.6, code: '036540', market: 'KR' },
      { name: '네패스', changePct: 2.9, code: '033640', market: 'KR' },
    ],
    '반도체 소재': [
      { name: '동진쎄미켐', changePct: 4.1, code: '005290', market: 'KR' },
      { name: '솔브레인', changePct: 3.5, code: '357780', market: 'KR' },
      { name: '한솔케미칼', changePct: 3.0, code: '014680', market: 'KR' },
      { name: 'SK머티리얼즈', changePct: 2.6 },
      { name: '이엔에프테크', changePct: 2.2, code: '102710', market: 'KR' },
    ],
    '테스트·계측': [
      { name: '리노공업', changePct: 3.4, code: '058470', market: 'KR' },
      { name: 'ISC', changePct: 2.9, code: '095340', market: 'KR' },
      { name: '티에스이', changePct: 2.5, code: '131290', market: 'KR' },
      { name: '엑시콘', changePct: 2.0, code: '092870', market: 'KR' },
      { name: '네오셈', changePct: 1.7, code: '253590', market: 'KR' },
    ],
    'AI 서버·기판': [
      { name: '이수페타시스', changePct: 5.2, code: '007660', market: 'KR' },
      { name: '대덕전자', changePct: 3.7, code: '353200', market: 'KR' },
      { name: '심텍', changePct: 3.1, code: '222800', market: 'KR' },
      { name: '코리아써키트', changePct: 2.4, code: '007810', market: 'KR' },
      { name: '티엘비', changePct: 2.0, code: '356860', market: 'KR' },
    ],
    전력기기: [
      { name: 'HD현대일렉트릭', changePct: 4.8, code: '267260', market: 'KR' },
      { name: 'LS ELECTRIC', changePct: 4.4, code: '010120', market: 'KR' },
      { name: '효성중공업', changePct: 3.9, code: '298040', market: 'KR' },
      { name: '일진전기', changePct: 3.2, code: '103590', market: 'KR' },
      { name: '제룡전기', changePct: 2.8, code: '033100', market: 'KR' },
    ],
    '특수가스·케미컬': [
      { name: '원익머트리얼즈', changePct: 2.4, code: '104830', market: 'KR' },
      { name: 'SK스페셜티', changePct: 2.0 },
      { name: '티이엠씨', changePct: 1.8, code: '425040', market: 'KR' },
      { name: '후성', changePct: 1.4, code: '093370', market: 'KR' },
      { name: '덕산테코피아', changePct: 1.1, code: '317330', market: 'KR' },
    ],
    '냉각·열관리': [
      { name: '케이엔솔', changePct: 3.1, code: '053080', market: 'KR' },
      { name: 'GST', changePct: 2.7, code: '083450', market: 'KR' },
      { name: '유니셈', changePct: 2.3, code: '036200', market: 'KR' },
      { name: '에스앤에스텍', changePct: 1.9, code: '101490', market: 'KR' },
      { name: '태경케미컬', changePct: 1.5, code: '006890', market: 'KR' },
    ],
    '전력망·ESS': [
      { name: 'LS', changePct: 2.9, code: '006260', market: 'KR' },
      { name: '효성중공업', changePct: 2.5, code: '298040', market: 'KR' },
      { name: '서진시스템', changePct: 2.2, code: '178320', market: 'KR' },
      { name: '삼화콘덴서', changePct: 1.8, code: '001820', market: 'KR' },
      { name: '비나텍', changePct: 1.4, code: '126340', market: 'KR' },
    ],
    '변압기·전선': [
      { name: '제룡전기', changePct: 3.3, code: '033100', market: 'KR' },
      { name: 'LS전선아시아', changePct: 2.8 },
      { name: '대한전선', changePct: 2.5, code: '001440', market: 'KR' },
      { name: '가온전선', changePct: 2.1, code: '000500', market: 'KR' },
      { name: '일진전기', changePct: 1.9, code: '103590', market: 'KR' },
    ],
    반도체: [
      { name: 'SK하이닉스', changePct: 8.9, code: '000660', market: 'KR' },
      { name: '삼성전자', changePct: 3.2, code: '005930', market: 'KR' },
      { name: '한미반도체', changePct: 7.4, code: '042700', market: 'KR' },
      { name: 'DB하이텍', changePct: 2.8, code: '000990', market: 'KR' },
      { name: '리노공업', changePct: 3.4, code: '058470', market: 'KR' },
    ],
    '반도체 소재·부품': [
      { name: '동진쎄미켐', changePct: 4.1, code: '005290', market: 'KR' },
      { name: '솔브레인', changePct: 3.5, code: '357780', market: 'KR' },
      { name: '한솔케미칼', changePct: 3.0, code: '014680', market: 'KR' },
      { name: '원익QnC', changePct: 2.7, code: '074600', market: 'KR' },
      { name: '월덱스', changePct: 2.3, code: '101160', market: 'KR' },
    ],
    '기계·장비': [
      { name: '두산로보틱스', changePct: 3.2, code: '454910', market: 'KR' },
      { name: 'HD현대인프라코어', changePct: 2.6 },
      { name: '두산밥캣', changePct: 2.1, code: '241560', market: 'KR' },
      { name: 'SNT다이내믹스', changePct: 1.8, code: '003570', market: 'KR' },
      { name: '현대에버다임', changePct: 1.5, code: '041440', market: 'KR' },
    ],
    IT하드웨어: [
      { name: '이수페타시스', changePct: 5.2, code: '007660', market: 'KR' },
      { name: '삼성전기', changePct: 3.4, code: '009150', market: 'KR' },
      { name: 'LG이노텍', changePct: 2.7, code: '011070', market: 'KR' },
      { name: '대덕전자', changePct: 3.7, code: '353200', market: 'KR' },
      { name: '심텍', changePct: 3.1, code: '222800', market: 'KR' },
    ],
    전기장비: [
      { name: 'HD현대일렉트릭', changePct: 4.8, code: '267260', market: 'KR' },
      { name: 'LS ELECTRIC', changePct: 4.4, code: '010120', market: 'KR' },
      { name: '효성중공업', changePct: 3.9, code: '298040', market: 'KR' },
      { name: '산일전기', changePct: 3.0, code: '062040', market: 'KR' },
      { name: '제룡전기', changePct: 2.8, code: '033100', market: 'KR' },
    ],
    화학: [
      { name: 'LG화학', changePct: 1.4, code: '051910', market: 'KR' },
      { name: '롯데케미칼', changePct: 1.1, code: '011170', market: 'KR' },
      { name: '금호석유', changePct: 0.9, code: '011780', market: 'KR' },
      { name: '한화솔루션', changePct: 0.7, code: '009830', market: 'KR' },
      { name: '코오롱인더', changePct: 0.5, code: '120110', market: 'KR' },
    ],
    운송: [
      { name: 'HMM', changePct: -1.8, code: '011200', market: 'KR' },
      { name: '대한항공', changePct: -1.2, code: '003490', market: 'KR' },
      { name: '팬오션', changePct: -0.9, code: '028670', market: 'KR' },
      { name: 'CJ대한통운', changePct: -0.7, code: '000120', market: 'KR' },
      { name: '현대글로비스', changePct: -0.4, code: '086280', market: 'KR' },
    ],
    유틸리티: [
      { name: '한국전력', changePct: -1.1, code: '015760', market: 'KR' },
      { name: '한국가스공사', changePct: -0.8, code: '036460', market: 'KR' },
      { name: '지역난방공사', changePct: -0.6, code: '071320', market: 'KR' },
      { name: 'SK가스', changePct: -0.3, code: '018670', market: 'KR' },
      { name: 'E1', changePct: -0.2, code: '017940', market: 'KR' },
    ],
  },
};

/** 분석 결과 조회 — FE 연동 시 이 함수만 API 호출(GET /api/analysis/:id)로 교체 */
export function getAnalysis(id: string): AnalysisResult {
  // 프로토타입: id와 무관하게 동일 mock을 반환한다
  void id;
  return analysisResult;
}
